### ISSUE TITLE
Servo on dcs bios 

### ISSUE THREAD

**Issue by MigSOBR** [dcs-bios/dcs-bios#101]
so i become this errror :
exit status 1
'ServoOutput' in namespace 'DcsBios' does not name a type

My code: 
#define DCSBIOS_DEFAULT_SERIAL
#include <Buttons.h>
#include <DcsBios.h>
#include <Encoders.h>
#include <ExportStreamListener.h>
#include <Leds.h>
#include <PollingInput.h>
#include <Potentiometers.h>
#include <Protocol.h>
#include <RingBuffer.h>
#include <Servos.h>
#include <Switches.h>

DcsBios::LED gearNoseDown(0x225c, 0x0200, 4);
DcsBios::LED gearLeftDown(0x225c, 0x0800, 2);
DcsBios::LED gearRightDown(0x225c, 0x2000, 3);
DcsBios::ServoOutput engineRpm(0x22a4, 9, 544, 2400);

void setup() {
  DcsBios::setup();
}

void loop() {
  DcsBios::loop();
}

 Mig SOBR ps i am a noob in c++ and java...

**Comment by jboecker** [comment]
`#include <DcsBios.h>` is enough (that includes everything else that comes with DCS-BIOS). The `#include <Servo.h>` needs to come first though.

DCS-BIOS will only provide the ServoOutput class if the Servo library has already been included. It does not include Servo.h for you. The reason is that the Servo library uses one of the Arduino's hardware timers, so it cannot be used with any other libraries that want to use the same timer.

I just checked and realized the documentation does not mention this.

**Comment by MigSOBR** [comment]
so what i must do? can you post the corret code?


MigSOBR

**Comment by jboecker** [comment]
The following compiles, but I did not have the time to test it on real hardware:

````c++
#include <Servo.h> // need to include the Servo library before DCS-BIOS so ServoOutput becomes available

#define DCSBIOS_DEFAULT_SERIAL
#include <DcsBios.h>


DcsBios::LED gearNoseDown(0x225c, 0x0200, 4);
DcsBios::LED gearLeftDown(0x225c, 0x0800, 2);
DcsBios::LED gearRightDown(0x225c, 0x2000, 3);
DcsBios::ServoOutput engineRpm(0x22a4, 9, 544, 2400);

void setup() {
DcsBios::setup();
}

void loop() {
DcsBios::loop();
}
````
