### ISSUE TITLE
KA-50 R800 VHF 2 frequency display problem.

### ISSUE THREAD

**Issue by deathrise200** [dcs-bios/dcs-bios#105]
Hello,

Loving dcs-bios but i've run into an issue.

I've been attempting to build a simple radio panel with a  7 segment display (max7219) to show frequency using the LedControl library to use on a few different aircraft. I have got the 7 seg display to work perfectly on the huey, mirage and a10c, but the ka-50 is being stubborn.

 I'm getting the following error when verifying the code:

C:\Users\Documents\Arduino\radio_ka_50_only\radio_ka_50_only.ino:31:82: warning: invalid conversion from 'void (*)(char*)' to 'void (*)(unsigned int)' [-fpermissive]

 DcsBios::IntegerBuffer r800Freq1RotBuffer(0x1910, 0x0ff0, 4, onR800Freq1RotChange);

                                                                                  ^

In file included from C:\Users\Documents\Arduino\libraries\dcs-bios-arduino-library-0.2.9\src/DcsBios.h:10:0,

                 from C:\Users\Documents\Arduino\radio_ka_50_only\radio_ka_50_only.ino:10:

C:\Users\Documents\Arduino\libraries\dcs-bios-arduino-library-0.2.9\src/internal/ExportStreamListener.h:97:4: note: initializing argument 4 of 'DcsBios::IntegerBuffer::IntegerBuffer(unsigned int, unsigned int, unsigned char, void (*)(unsigned int))'

    IntegerBuffer(unsigned int address, unsigned int mask, unsigned char shift, void (*callback)(unsigned int)) : Int16Buffer(address) {

    ^
This is the code i'm using (excluding the setup):
#define DCSBIOS_IRQ_SERIAL
#include <DcsBios.h>
#include <LedControl.h>

//pin 2 is connected to the DataIn 
//pin 4 is connected to the CLK 
//pin 3 is connected to LOAD
LedControl lc=LedControl(2,4,3,1);

/* below is for the KA-50 radio.
*/

void onR800Freq1RotChange(char* newValue) {
    lc.setChar(0,6,newValue[0],false);
    lc.setChar(0,5,newValue[1],false);
}
DcsBios::IntegerBuffer r800Freq1RotBuffer(0x1910, 0x0ff0, 4, onR800Freq1RotChange);

void onR800Freq2RotChange(unsigned int newValue) {
    lc.setChar(0,4,newValue,true);
}
DcsBios::IntegerBuffer r800Freq2RotBuffer(0x1914, 0x00ff, 0, onR800Freq2RotChange);

void onR800Freq3RotChange(unsigned int newValue) {
    lc.setChar(0,3,newValue,false);
}
DcsBios::IntegerBuffer r800Freq3RotBuffer(0x1914, 0xff00, 8, onR800Freq3RotChange);

void onR800Freq4RotChange(char* newValue) {
    lc.setChar(0,2,newValue[0],false);
    lc.setChar(0,1,newValue[1],false);
}
DcsBios::IntegerBuffer r800Freq4RotBuffer(0x1916, 0x00ff, 0, onR800Freq4RotChange);

It causes the error message, but it still lets me upload it to the board(arduino uno). it just displays the complete wrong numbers and even some letters on the 7 segment display.

I'm probably making a simple mistake, but any help would be greatly appreciated.

**Comment by jboecker** [comment]
Switch the control reference to "Advanced" view and use the string outputs on the "Frequency 1" through "Frequency 4" controls like this:
````void onR800Freq1Change(char* newValue) {
    /* your code here */
}
DcsBios::StringBuffer<2> r800Freq1StrBuffer(0x190e, onR800Freq1Change);````

The "simple" view tries to guess the code snippet that is right for the majority of cases, but it's a very simple heuristic that sometimes gets things wrong.

The "Frequency 1 rotary" etc. outputs export the rotation of the knob itself, which is only interesting if you are implementing software that talks to DCS-BIOS and wants to know when to send the next command to influence a frequency dial (as long as the knob turn animation is still playing, DCS ignores all further inputs for that knob).

The error message you are seeing is caused by your callback function (e.g. `onFreqRot1Change`) expecting a parameter of type `char*` when the data is an `unsigned int`. I don't know how you ended up with that, as the control reference code snippet for the "Frequency 1 rotary" has the correct data type.

**Comment by deathrise200** [comment]
Ah I see! Thanks a bunch for pointing that out. Pretty new to all this, you saved me a lot of head scratching, works perfectly now. 

Many thanks.
