### ISSUE TITLE
Some elements missing from control reference

### ISSUE THREAD

**Issue by Gadroc** [dcs-bios/dcs-bios#44]
In particular the address for the HSI Heading output is missing from the control reference.  It looks like it's caused by line 235:
```defineFloat("HSI_HDG", 34, {0, 1}, "HSI", "HSI Heading")```
and line 865:
```defineVariableStepTumb("HSI_HDG", 45, 3001, 45, 1.0, "HSI", "Heading Select Knob")```

Both use the same ID, which seems to confuse the documentation generator.  I was able to deduce the address for the HSI Heading to be 0x104c based on the address of surrounding items.

**Comment by jboecker** [comment]
Looking a bit closer, the whole HSI heading/course related stuff is messed up and confusing right now.

In DCS, the relevant argument numbers are:
````
34 -- current airplane heading as shown on HSI
36 -- position of the heading bug (selected heading)
44 -- rotation of the course select knob
45 -- rotation of the heading select knob
47 -- selected HSI course
````

In A10C.lua, there is:

````lua
-- line 235
defineFloat("HSI_HDG", 34, {0, 1}, "HSI", "HSI Heading")

-- line 238, 239
defineFloat("HSI_HDG_BUG", 36, {0, 1}, "HSI", "HSI Heading Bug")
defineFloat("HSI_CRS_BUG", 47, {0, 1}, "HSI", "HSI Course")

-- line 249, 250
defineFloat("HSI_HDG_KNOB", 45, {0, 1}, "HSI", "HSI Heading Knob")
defineFloat("HSI_CRS_KNOB", 44, {0, 1}, "HSI", "HSI Course Knob")

-- line 864, 865
defineVariableStepTumb("HSI_CRS", 45, 3002, 44, 1.0, "HSI", "Course Select Knob")
defineVariableStepTumb("HSI_HDG", 45, 3001, 45, 1.0, "HSI", "Heading Select Knob")
````

* line 865 conflicts with line 235 because they both define a control with the identifier "HSI_HDG"
* lines 249 and 250 are redundant, because the knob rotations are already exported as part of lines 864 and 865

I suggest the following changes:
* get rid of the current HSI_HDG_KNOB and HSI_CRS_KNOB definitions (lines 249, 250)
* instead, rename HSI_CRS / HSI_HDG defined in lines 864,865 to HSI_CRS_KNOB / HSI_HDG_KNOB
* rename HSI_CRS_BUG to HSI_CRS (because there is no "course bug")

We will end up with:
* HSI_HDG
  * output: current heading as shown on HSI
* HSI_HDG_BUG
  * output: currently selected heading (position of heading bug)
* HSI_CRS
  * output: currently selected course
* HSI_HDG_KNOB
  * input: turn heading bug selector
  * output: rotation of heading selector knob
* HSI_CRS_KNOB
  * input: turn course selector
  * output: rotation of course selector

When I get back to my dorm room, I can make the neccessary changes (replacing lines 238,239 with dummy allocations to avoid moving all the other offsets around).

**Comment by jboecker** [comment]
I forgot about this one. Should be fixed now.
