### ISSUE TITLE
UH-1H: FM Radio - Define Freq String

### ISSUE THREAD

**Issue by OlHall** [dcs-bios/dcs-bios#57]
Hi,

Can you add a function/defineString to the UH-1H to provide a StringBuffer for the FM frequency please?

Thanks

**Comment by jboecker** [comment]
That information is already available as part of the individual knobs. The idea is to avoid exporting redundant information to keep the amount of data transmitted to a minimum. 

On the other hand, that "policy" was born when I started writing DCS-BIOS and had no idea how problematic it would be to fit everything over a slow serial port. Adding a few redundant string values that rarely change probably won't hurt anything and the performance loss incurred by calculating them 30 times a second in the Lua code is probably not even measurable.

I'll think about it.
If we add this, we should also (by the same reasoning) add string outputs for the A-10C's VHF AM and VHF FM radio frequencies.

**Comment by OlHall** [comment]
However you look at it, it's inconsistent.

All of the other Huey radios have a Freq string - so I'd have thought either they all should, or all shouldn't.  It's easier to present a string on a panel than it would be to instantiate 4 different IntegerBuffer objects, but I can go either way.

**Comment by jboecker** [comment]
There's a twisted way in which it is consistent: string outputs are only provided where the same information is not otherwise available (i.e. you can't deduce the frequency from the rotation of the knobs). The other Huey radios don't export knob rotation at all (because their internals in DCS work differently), so they get the frequency as a string output.

The UHF frequency string in the A-10C is still consistent with this: while you can deduce the UHF frequency from the dial positions, the string value actually captures the display content, so it is empty (all spaces) when power is off and it briefly contains "***.***" while the radio powers up or when the "display test" button is pressed.

Because (given what I know now) this shouldn't negatively impact performance, I will add string exports to all radios in the UH-1H and A-10C that are currently missing them.

**Comment by OlHall** [comment]
Ok - I follow that... so is it something else that led to FM-Freq1 and FM-Freq4 being allocated StringBuffer<1> but FM-Freq2 and 3 don't... the only difference appears to be the range that these values can take (Freq2 & 3 being 0-9)?

**Comment by jboecker** [comment]
Correct. For FREQ2 and FREQ3, a simple lcd.print(value) or lcd.print(itoa(value)) or lcd.print('0'+value) will do the trick, because the integer position values match what shows up on the frequency display.

FREQ1 and FREQ4 got string exports because those values do not match. It's still redundant information -- I think my reasoning at the time was that I wouldn't want to get bug reports of "this reports the wrong value". It also started with the A-10C radios, where the display range is " 3" to "15" and simply printing an integer value (plus 3) would require additional logic to deal with 1-digit vs. 2-digit numbers.

**Comment by OlHall** [comment]
Understood - many thanks!

I think I'm making a meal of it because I'm using the newer code that makes using onDCSBiosWrite() redundant, so I'd still end up creating an IntegerBuffer (or IntegerData in my version) for each chunk of packed data - so to use that "value", I'd have to create/test for isDirty() 4 different objects rather than one.

I'm happy to use whichever method is deemed the most efficient though.  Thanks again.
