### ISSUE TITLE
CDU display Issue....

### ISSUE THREAD

**Issue by yijinam** [dcs-bios/dcs-bios#65]
Hi.. I'm a big fan of DCS-Bios..Thank you .... Ian
 i'm making A-10c CDU....thesedays

I bought 4.3" TFT LCD and connected with Arduino mega using UTFT library..
and Try to export CDU display...

It's awesome works but...1) some delay happens and 2) Some font is not working...like [],  ->(arrow)
I think becasuse of the font issue ,the delay could happend...Because..
As the photo below, I exported CMSP and CMSC together...It's working very well they don't have any special font..

I dont have much software Knowledge ,   So, Please let me know How I can fix this issue ......?
![img_20150612_223708 1](https://cloud.githubusercontent.com/assets/9463529/8142555/b0651bc2-11c3-11e5-8412-39143efebff8.jpg)

**Comment by jboecker** [comment]
The special characters in the CDU font are not in the ASCII standard, so the font you are using (I assume one that comes with the UTFT library?) will not include them. You need to figure out how to modify that font. See [this commit message](https://github.com/dcs-bios/dcs-bios/commit/515bb3c982c28e7bb011eb83f64fbe77abdc31e5) for the mapping of symbols to character codes.

"Some delay happens" is way too unspecific for a bug report. How long is it? When exactly does it happen? If it only happens when you switch the CDU page, then the Arduino is probably too slow to push a full screen's worth of pixel data to the display fast enough so the human eye won't notice. See if the delay still happens if you only export one or two lines of the CDU display (so the amount of data that is changing at once is compareable to the CMSP and RWR displays).

**Comment by yijinam** [comment]
Thanks for the hints ...Ian,,,

but I don't have any knowledge so, i couldn't know that how I can  modify that font..

Yes I use the font that comes with the UTFT library .How can I add the new fonts? 

Could you explain more about that please ?

**Comment by yijinam** [comment]
Thanks for the hints ...Ian,, 

I've solve the font issue ,,,,very happy...
 but Still delay happens....

The delay happens when switch the CDU page .... it take about 1~2 minute.....
 I tihnk Arduino is probably too slow to push a full screen of CDU as you said........I'll test more....

**Comment by jboecker** [comment]
This is likely a problem with the way serial communication is handled at the moment. The default Arduino way is to store incoming data in a small 64-byte buffer until Serial.read() is called. If Serial.read() is not called frequently enough (for example because the code is busy talking to the display), that buffer becomes full and further incoming data is ignored.

Eventually, the display will become fully up-to-date even though incoming data was missed because DCS-BIOS periodically resends data even if it did not change. This happens at a rate of four bytes per update (every 33 ms), which results in everything being resent within about 10 seconds. If it takes more than that to update the whole display, your code likely needs more than ~25 ms to send two changed characters to the display.

The next version of the Arduino library should fix this particular problem by moving all communication-related code into interrupt handlers. However, I have no ETA on that.

In the meantime, you can try to [increase the buffer size.](http://www.hobbytronics.co.uk/arduino-serial-buffer-size)

Another thing that might help is to only update the display one character at a time. When you get data from DCS-BIOS, write it to a buffer in memory. In your loop() function, update only a single character, so that the serial receive buffer will be emptied between each character that has been written to the display.

**Comment by jboecker** [comment]
This should be fixed by using interrupt-based serial communication or an RS-485 bus. As of right now, both of those features are available in the "rs485" branch; they will eventually be merged into master, too.
