### ISSUE TITLE
Dcs-bios + raspberry pi?

### ISSUE THREAD

**Issue by Nasty76** [dcs-bios/dcs-bios#71]
Hello there first i need say very impressive job with dcs-bios , easy to use , and work like charm. 
My issue is i have play little arduino and raspberry pi , and i can sent data arduino -> raspberry pi -> dcs game computer , well all button press go in game but leds not work in my script , any idea how i can use linux socat command. 
my example script is:
#!/bin/bash
chmod 666 /dev/ttyACM0

stty -F /dev/ttyACM0 500000
stty -F /dev/ttyACM0 raw
socat udp-sendto:192.168.1.80:7778 /dev/ttyACM0&

chmod 666 /dev/ttyACM1

stty -F /dev/ttyACM1 500000
stty -F /dev/ttyACM1 raw
socat udp-sendto:192.168.1.80:7778 /dev/ttyACM1

**Comment by jboecker** [comment]
Your socat command will only send data in one direction.

The address specification for the serial port works both ways, but "udp-sendto:192.168.1.80:7778" is a unidirectional data flow.

Option 1:
    socat udp-sendto:192.168.1.80:7778!!udp-listen:12345,reuseaddr /dev/ttyACM0
That will listen on UDP port 12345 on the Raspberry Pi and forward the received data to the serial port. The "reuseaddr" socket option ensures that multiple socat instances can listen to the same UDP port (because Linux is awesome and allows this to work).
To get the data to arrive at your Raspberry Pi, you have to edit your BIOSConfig.lua file (there is already a commented-out line for a UDPSender in there that you can modify).

Option 2:
    socat tcp-connect:192.168.1.80:7778 /dev/ttyACM0
DCS-BIOS also offers a TCP server you can use. This command simply uses a TCP connection, which works both ways.

**Comment by Nasty76** [comment]
OK , thanks for super fast help , that look just right , how about when add another arduino /ttyACM1 
same script work or do i need dcs-bios make 2 separate porst where i communicate raspberry pi ? 
I test that tonight , Thanks for make awesome software another sim hobbyist , dcs-bios is super easy to use , and work like charm.

**Comment by jboecker** [comment]
If you were running socat on Windows, you'd have to use separate ports (or mess with multicast UDP). Because your RasPi runs Linux, we can use the "reuseaddr" socket option to make both socat instances receive the same data (without the option, the second instance would fail to start with a "port already in use" error message).

**Comment by Nasty76** [comment]
Ok thanks for fast answer i test system later today

----- Alkuperäinen viesti -----
Lähettäjä: "jboecker" <notifications@github.com>
Lähetetty: ‎9.‎9.‎2015 14:00
Vastaanottaja: "dcs-bios/dcs-bios" <dcs-bios@noreply.github.com>
Kopio: "Nasty76" <nasty76@gmail.com>
Aihe: Re: [dcs-bios] Dcs-bios + raspberry pi? (#71)

If you were running socat on Windows, you'd have to use separate ports (or mess with multicast UDP). Because your RasPi runs Linux, we can use the "reuseaddr" socket option to make both socat instances receive the same data (without the option, the second instance would fail to start with a "port already in use" error message).

**Comment by Nasty76** [comment]
Your 1 option was sucess some why I need split send and receive separate line but after that both arduino work as charm. I think this trick is good to add documentation now i have situation where cockpit not take CPU time my game comp  :) I test how many arduinos one pi can host via USB hub. I need say thanks for awesome job I really want thanks guys who write some awesome software free l. I recomend raspberry to use minibian image that is much light and work fast than official release.
