### ISSUE TITLE
Question regarding controlling the Huey collective via dcs-bios

### ISSUE THREAD

**Issue by oetroc** [dcs-bios/dcs-bios#76]
Hello,

First off, thank you for this excellent interface into DCS world!

I am working on porting the Arduino drivers into my TivaC project. I am currently able to RX the cockpit state of the UH-1H via the export stream, and I was able to control LEDs tied to the Arm and Safe indicators on the Armament panel. Will work on porting over the pollingInput functionality to my project soon.

My question: Is it possible to control the collective position (i.e. collective up/down) via dcs-bios? 

So far, looking through the control reference I cannot seem to find any mention as to how to control the physical position of either the cyclic or collective. My original intent was to use a potentiometer to relay the angular position of my home made collective to DCS.

Once again, thank you for this awesome bit of software.

**Comment by jboecker** [comment]
Since you can't click and drag the collective in the virtual cockpit, it is not supported by DCS-BIOS. It might be possible to find a way to set it from Export.lua by looking at the input definition lua files, but I never looked into that because I figured that the primary flight controls would use normal USB controllers anyway.

By the way the DCS-BIOS Arduino library works out of the box on the Tiva C launchpad using [Energia](http://energia.nu). My [Altimeter Demo](https://www.youtube.com/watch?v=gp8maRS7XB0) was powered by a Tiva C Launchpad.

**Comment by oetroc** [comment]
I figured that was the case. By porting over, I mean simply removing the C++ abstraction and distilling it down to the C components. The usb-dev-serial sample project included in TivaWare is a C project, so simply copying and pasting wouldn't work. I'm very comfortable with C, just have to stop being lazy and make the the upgrade to OOP. I will use the usb-gamepad project to setup a simple HID Gamepad device and use that for my collective and throttle position input (although I do see that you support the Huey throttle via dcs-bios). Thanks for the info.
