### ISSUE TITLE
Common Data Airspeed?

### ISSUE THREAD

**Issue by jdmkramer** [dcs-bios/dcs-bios#79]
I see altitude, position, and heading are available. Should I try to extrapolate airspeed from position data, or will it be made available some time?

**Comment by jboecker** [comment]
I tried adding that today, using the LoGetIndicatedAirSpeed() and LoGetTrueAirSpeed() Lua functions. In the A-10C, LoGetIndicatedAirSpeed() always returns zero and LoGetTrueAirSpeed() returns a number that seems to be somewhat related to airspeed, but is way lower than the TAS displayed on the CDU.

Since there does not seem to be a universal method to get the airspeed, you either need to interpolate from the position updates or you need to read the actual instrument (i.e. in case of the A-10C, use the positions of the airspeed needle).

I am closing this issue for now. If someone finds a way to get the airspeed that works across all aircraft, I will of course add it to the CommonData module.
