### ISSUE TITLE
hi, look for example c++ code and interested in f15 

### ISSUE THREAD

**Issue by steveh2112** [dcs-bios/dcs-bios#80]
hi, i just found your project and would like to use it on a windows platform. do you have an example c++ file i can look at for all the UDP stuff, it would save me a lot of time creating it from scratch. i'm also interested in helping out add the f15 to your library

thx steve

**Comment by steveh2112** [comment]
i just wrote a simple multicast listener (below) and i installed  dcs-bios-0.4.1 and export.lua in DCS scripts. then i ran DCS, whent to the a10c, and i don't see any multicast data packets. do i need to request data from DCS or should it be just sent all the time? sorry but i don't get this at all. here's my code: thanks, steve

#include "stdafx.h"
#include <winsock2.h>
#include <Ws2tcpip.h>
#include <stdio.h>

// Link with ws2_32.lib
#pragma comment(lib, "Ws2_32.lib")

int _tmain(int argc, _TCHAR* argv[])
{

    char* multicast_ip = "239.255.50.10";
	unsigned short multicast_port = 5010;
	SOCKADDR_IN multicast_addr;
	WSADATA wsaData;
	int hr;
	BOOL bOptVal = TRUE;
	ip_mreq mreq;
	int max_length = 16;

	WSAStartup(MAKEWORD(2,0), &wsaData);

	SOCKET sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
	if (sock == INVALID_SOCKET) {
        wprintf(L"socket failed with error %d\n", WSAGetLastError());
        return 1;
    }

	// construct bind structure
	memset(&multicast_addr, 0, sizeof(multicast_addr));
	multicast_addr.sin_family = AF_INET;
	multicast_addr.sin_addr.s_addr = htonl(INADDR_ANY);
	multicast_addr.sin_port = htons(multicast_port);

	hr = bind(sock, (struct sockaddr *) &multicast_addr, sizeof(multicast_addr));
	if (hr != 0) {
        wprintf(L"bind failed with error %d\n", WSAGetLastError());
        return 1;
    }
	/* Specify the multicast group */
	mreq.imr_multiaddr.s_addr = inet_addr(multicast_ip);
	/* Accept multicast from any interface */
	mreq.imr_interface.s_addr = htonl(INADDR_ANY);
	/* Join the multicast address */
	hr = setsockopt(sock, IPPROTO_IP, IP_ADD_MEMBERSHIP, (char FAR *) &mreq, sizeof(mreq));

	int optval = 8;
	hr = setsockopt(sock,IPPROTO_IP,IP_MULTICAST_TTL, (char*)&optval,sizeof(int));

	hr = setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (char *)&bOptVal, sizeof(bOptVal));

	int timeout = 1000; // 1 sec
	setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, (char *) &timeout, sizeof(timeout));

	while (true)
	{
		char buffer[4096] = { 0 };

		int i = recvfrom(sock, buffer, 4096, 0, NULL, 0);
		if (i == SOCKET_ERROR) {
			wprintf(L"recvfrom failed with error %d\n", WSAGetLastError());
			Sleep(1000);
			continue;
		}

		int wut = WSAGetLastError();
	}
	WSACleanup();
    return 0;
}

**Comment by steveh2112** [comment]
i should mention i get a 10060 timeout from the recvfrom indicating no data. i'm running this on the same computer as DCS. thanks

**Comment by jboecker** [comment]
I don't see anything wrong with this code. That said, I also have zero experience with C++ programming on Windows.

As long as there is a running, unpaused DCS: World mission you should get some data approximately once every 33 ms. You can use the following socat command to connect the multicast data stream to the terminal (to verify that data is being sent):

````socat -v UDP4-RECV:5010,ip-add-membership=239.255.50.10:127.0.0.1,reuseaddr -````

Adding F-15 support sounds great, although I haven't looked into FC3 aircraft much so far. You'll have to test the various LoGet... functions and see which of them apply to the F-15.

**Comment by steveh2112** [comment]
thanks. i downloaded socat (.exe and all .dll) from here
https://github.com/jboecker/dcs-arduino-example/tree/master/socat
and downloaded cygwin on windows10 x64
when i run that socat comand, i get
./socat: line 5: syntax error near unexpected token `newline'
./socat: line 5: `<!DOCTYPE html>'

i'm donwloading gcc right now (4% and i've been downloading for 30mins so i will take a while.) so i'll try that soonish.

one think i noticed, in my code i didn't specify 127.0.0.1. not sure how to do that as i have very little experience with multicast.

also, just to check on the DCS side. all i did was place dcs-bios-0.4.1 and Export.lua in
C:\Users\me\Saved Games\DCS\Scripts
for good luck i also pout the same stuff in DCS Warthog and DCS.openbeta

is that all that is necessary on the DCS side or did i miss something? i went into instant action on the a10c but didn't see any action on my tool. still trrying to get socat working.

thx steve

**Comment by jboecker** [comment]
AFAIK the 127.0.0.1 just tells socat the network interface it should add to the multicast group.

Check dcs.log for errors. You should have a file called C:\Users\me\Saved Games\DCS\Scripts\DCS-BIOS\BIOS.lua. If you don't, you got the folder structure wrong (and it should complain in dcs.log that the file cannot be found).

If there is no obvious error in dcs.log, try if you can get the [interactive control reference](https://www.youtube.com/watch?v=MoVoa-BUOkQ) Chrome add-on working. That uses TCP instead of multicast UDP. If that works, it may be a firewall problem (the Windows firewall should be no problem, but other users have had problems with third-party firewalls and multicast UDP).

**Comment by steveh2112** [comment]
hum, stupid me, i copied the whole dcs-bios-0.4.1 to DCS/Scripts, i should have gone into dcs-bios-0.4.1/Scrips and copied DCS-BIOS and Export.lue

anyhow, now my test program is running and i'm getting a couple of hundred bytes per recvfrom

so i guess i need to read the a10c.lua file to figure out what's in there right?

also, any docs that will tell me how to write a lua file for f15?

thanks so much for the great support

steve

**Comment by jboecker** [comment]
Start here:
http://dcs-bios.a10c.de/docs/v0.4.1/developerguide.html#_adding_an_export_module_for_your_aircraft

Once you have added an F-15 module, look at CommonData.lua for inspiration. Some parts of A-10C.lua may also be of interest, especially those which have to get their data with custom Lua code (e.g. radio frequencies, CDU display text). Most of the existing functions (definePushButton, defineFloat, etc) will be useless to you because they rely on cockpit arguments, and we don't have access to those in FC3 aircraft.

If you have not already done so, definitely hook up the [DCS Witchcraft Lua console](https://github.com/jboecker/dcs-witchcraft) to your Export.lua environment. To do that, you can ignore the setup instructions in the README (those are only needed for the mission scripting environment). All you need to do is to call WitchcraftExport.lua from your Export.lua file like this:
````lua
dofile(lfs.writedir()..[[Scripts\witchcraft\WitchcraftExport.lua]])
````

Then run witchcraft\windows\witchcraft.cmd, browse to localhost:3000 and click "Lua Console".

The Lua console is essential to quickly look at what functions are available and see what values they return.

**Comment by steveh2112** [comment]
thanks again, you are really helpful. so i modified a10c.lua to this
BIOS.protocol.beginModule("A-10C", 0x1000)
BIOS.protocol.setExportModuleAircrafts({"A-10C"})
local document = BIOS.util.document
local defineFloat = BIOS.util.defineFloat
defineFloat("HSI_HDG", 1, {0, 1}, "HSI", "HSI Heading")
BIOS.protocol.endModule()

just so i've got a more manageable problem. i'm getting data and the correct sync code 0x55 * 4
but i've looked at the data as both ints and floats and nothing seems to correlate to the heading.

any advice please? thx

**Comment by jboecker** [comment]
Every animation in the cockpit (lights, gauge needles, switches, etc) is controlled by a cockpit argument which is generally in the range from 0 to 1, sometimes from -1 to 1. For aircraft with a clickable cockpit, we have access to these cockpit arguments from Export.lua.

When an angle is involved, 0 usually means straight up, 0.25 points to the right, etc. The defineFloat function maps that to an integer value from 0 to 65535 (because floats are annoying to deal with on a microcontroller).

So to convert the heading into a value you see in the export data:
exported_value = heading / 360 * 65535

You can see this value in the interactive control reference.
To understand more about cockpit arguments, you could also play around with the ED Model Viewer.

But you don't need that anyway because there is no known way to get cockpit arguments in FC3 aircraft like the F15.


Start by understanding what values you have access to. The best way is to get the Lua Console set up and play around in that (e.g. type in "return LoGetAltitudeAboveSeaLevel()" and press Ctrl+Return to execute that snippet of code).

To find out what functions you have access to:

* official ED blog post introducing Export.lua: https://web.archive.org/web/20141130081345/http://www.digitalcombatsimulator.com/en/dev_journal/lua-export/
*

**Comment by steveh2112** [comment]
thanks again so much for your help.

so i went back to basics, wrote a simple Exports.lua to read a few params like airspeed, pitch, roll, etc and write to a log file. all works great.

so i try to open a TCP socket but what ever i do, it fails. 

here my exports.lua
=================================
local log_file = nil

function LuaExportStart()

-- 1) File
	log_file = io.open("C:/Users/me/Saved Games/DCS/Logs/Export.log", "w")

-- 2) Socket		
	package.path  = package.path..";.\\LuaSocket\\?.lua"
	package.cpath = package.cpath..";.\\LuaSocket\\?.dll"
	socket = require("socket")
	host = host or "localhost"
	port = port or 27015
	c = socket.try(socket.connect(host, port)) -- connect to the listener socket
	c:setoption("tcp-nodelay",true) -- set immediate transmission mode
end

function LuaExportBeforeNextFrame()
end
function LuaExportAfterNextFrame()
end

function LuaExportStop()

-- 1) File
	if log_file then
		log_file:write("Closing log file.")
		log_file:close()
		log_file = nil
	end	
-- 2) Socket
	socket.try(c:send("quit")) -- to close the listener socket
	c:close()
end

function LuaExportActivityNextEvent(t)

	local altBar = LoGetAltitudeAboveSeaLevel()
	local altRad = LoGetAltitudeAboveGroundLevel()
	local pitch, bank, yaw = LoGetADIPitchBankYaw()
	local tas = LoGetTrueAirSpeed()

-- 1) File	
	log_file:write(string.format(
"altBar=%.2f, pitch=%.2f, bank=%.2f tas=%.2f\n", 
altBar, 57.3*pitch, 57.3*bank, tas))

-- 2) Socket
	socket.try(c:send(string.format(
"altBar=%.2f, pitch=%.2f, bank=%.2f tas=%.2f\n", 
altBar, 57.3*pitch, 57.3*bank, tas)))


	local o = LoGetWorldObjects()
	for k,v in pairs(o) do
		log_file:write(string.format(
"ID=%d name=%s UnitName=%s GroupName=%s LatLong=(%f,%f)\n", 
k, v.Name, v.UnitName, v.GroupName, v.LatLongAlt.Lat, v.LatLongAlt.Long))
	end

	return t+0.2
end
==================

but whatever i do, i cannot get the socket to open.

i've tried opening a telnet  session to localhost port 27015 but the connection just times out.

i wonder what i'm mission here? or do i need to switch to multicast like your program does?

sorry for this, i know this is not a DCS-BIOS question but i'm just a bit frustrated with it. but on the plus side, i have found a way to get all the telemetry data i need, its just a question of getting it onto the network right now.

thx steve

**Comment by jboecker** [comment]
You have written a TCP client application that tries to connect to localhost:27015. The connection attempt fails because you have no server application that is listening for connections.

If you want to implement a TCP server in Lua, look up a tutorial on how to do that (in DCS-BIOS, this is implemented in ProtocolIO.lua).
