### ISSUE TITLE
DCS-BIOS & Multiplayer

### ISSUE THREAD

**Issue by pdmarsh** [dcs-bios/dcs-bios#95]
I am using Saitek instrument panels along with Flightpanels software that uses DCS-BIOS for switch and other panel configuration.  More often than not, those switches and panels, e.g. radio, that use DCS-BIOS do not work when I am in multiplayer missions.  However, on occasion they do work.  I have never had a problem getting the panels to work when in single player missions.  Those switches and/or buttons that are configured as keyboard emulators, i.e. not using DCS-BIOS commands, always work whether in multi or single player.

I'm assuming that this is a DCS-BIOS issue, although it could be related to Flightpanels.  I would welcome any feedback you might have on this behavior.

Thanks,
Paul Marsh

**Comment by jboecker** [comment]
MP servers can disable certain subsets of Export.lua features. There are three settings that control this. Each setting controls a different subset of features and can be turned on and off independently from the other two in the "Advanced settings" dialog when creating a server.

Setting | Name in networkSettings.cfg | Description
--- | --- | ---
Allow object export | allow_object_export | Disabling this turns off LoGetWorldObjects(), which can be used to get a list of every unit in the game. Used by TacView.
Allow Sensor's Export | allow_sensor_export | Disables functions related to exporting RWR content
Allow Player's Export | allow_ownship_export | Disables various functions that return flight data about your own aircraft

[This post on the ED forums](http://forums.eagle.ru/showpost.php?p=2769121&postcount=185) has a detailed list of what is disabled by the different options.

allow_ownship_export also disables the LoGetSelfData() function which DCS-BIOS relies upon for some things in the CommonData module and, more importantly, to determine which type of aircraft you are in.

I'll have to think about how to best address this problem. Disabling the CommonData export when that information is not available wouldn't be too hard to implement, but I don't know if there is another way to determine the current unit type.

**Comment by pdmarsh** [comment]
Thank you very much for responding.  This explains a lot.  Not only was I seeing differences from MP session-to-session, but even from function-to-function in the same session, i.e. some DCS-BIOS configurations would work while others would not.

If there is no downside to enabling all of these export settings, I'll the people that usually host our missions to change those settings.  We have seen this issue with TacView and "allow_object_export."

Thanks again,
Paul

**Comment by jboecker** [comment]
The only two LoGet* functions that DCS-BIOS uses are LoGetModelTime() and LoGetSelfData(), and LoGetModelTime() is always available.

If LoGetSelfData() returns nil (which I assume it does when allow_ownship_export is off), DCS-BIOS will assume you are in spectator mode and won't export anything except the aircraft name, which will be "NONE".

Is that what you mean by function-to-function differences in the same session?

Regarding the export settings, here's my understanding about why each of these exists.

allow_object_export has been around for a long while now, because it's quite obvious that having the list of all units in the game (including their current locations) that LoGetWorldObjects() gives you can be used to cheat in MP.

allow_sensor_export disables functions that can be used to grab RWR data. I think there are programs that use this information to make the RWR more powerful than it is in-game (for example they add reliable threat type or range information) and maybe even add some RWR functionality for aircraft that don't even have one.

The only important reason for disabling allow_ownship_export that I can see is that it will provide location data for a moving map (or a map of you and all your squadmates if someone networks those computers). It also disables access to flight data about your own aircraft, but most of that is displayed on a gauge in the cockpit anyway, so this only becomes interesting once that gauge breaks.

I have put in a feature request with ED (bug report #35312) for a function that returns the own unit type regardless of MP server settings. If they implement it, fixing this will be trivial. If they don't, I can think of several ugly workarounds (some way for you to tell DCS-BIOS what aircraft you are about to fly).

**Comment by pdmarsh** [comment]
Thanks for the additional information.  The best example I can give of
function-to-function differences is with the Saitek Radio Panel.  The radio
selector knob on the actual panel is configured to choose which radio in
the sim is being adjusted.  When the knob is set to "XPDR" you can change
the radio that your are transmitting on in the sim, e.g. radio 1, 2 or 3.
In MP, this works fine.  However, when the knob on the Saitek Radio Panel
is set to "COM 1," I should be able to change the frequency of the AM radio
in the Huey, for example.  This does not work.  So one DCS-BIOS
configuration is working but another is not in the same session.

I hope that explains what I meant.

Thanks,
Paul

**Comment by jboecker** [comment]
That's not a DCS-BIOS feature. It may be a feature of whatever radio add-on software you are using.

In other words, none of the aircraft controls in DCS-BIOS work because LoGetSelfData() returns nil and DCS-BIOS thinks we are in spectator mode.

**Comment by pdmarsh** [comment]
Interesting.  As good as Flightpanels is [http://forums.eagle.ru/showthread.php?t=137670], it does have its quirks.

Thanks again for all of the info.  For now, the folks that host most of the sessions I fly in are happy to enable the export.

Paul
