### ISSUE TITLE
A-10C: Is the ILS Power LED the wrong way around?

### ISSUE THREAD

**Issue by fdroege** [dcs-bios/dcs-bios#98]
It might be just me, but... I'm currently trying to build an ILS Panel for use in different planes (planning for the future...), so I decided to have a small green LED built in telling me if ILS is on or off. But when testing this with my breadboard, the LED went dark when I switched ILS on and vice versa.

Am I overlooking something, is this maybe by design? Or have I found a bug? I know I can probably code around this somehow, but I'd prefer the single line option as below. 

```
#define DCSBIOS_IRQ_SERIAL

#include "DcsBios.h"

DcsBios::LED ilsPwr(0x1168, 0x0010, 3);

void setup() {
  DcsBios::setup();
}

void loop() {
  DcsBios::loop();
}
```

**Comment by jboecker** [comment]
The A-10C does not have an ILS LED. What you are accessing is the state of the ILS power switch. The control reference is dumb, it doesn't know that's a switch and not an LED -- it only sees a value that has two possible states, so it offers the LED snippet in Advanced view.

Note that as long as the switch is ON, the LED will turn on regardless of whether the ILS actually has power (for example, it will still be on when the battery is off).

That said, your sketch should work, because the ILS power switch value happens to be the right way around (0 for off, 1 for on). Try changing the pin number to 13 to use the built-in LED on the Arduino board.

Check your wiring. The anode (+) of the LED should be connected to the Arduino board, the cathode (-) should go to ground (the current limiting resistor can go on either side in series with the LED).

If you connected the anode (+) to VCC and the cathode (-) to the Arduino board, you'd get the inverted behavior you are seeing.

**Comment by fdroege** [comment]
Thank you for the explanation! I was indeed wondering where the LED in the control reference came from. I knew the A-10C has none for ILS, but I deemed it some eye candy nonetheless. 

I checked my wiring and also tried pin 13. All correct. My LED and the onboard LED show the same behaviour. So I installed the Chrome extension from your YT video to see the actual value of "ILS Power" (should have done that yesterday before posting, my bad...) and behold! the value is "1", and the LEDs are ON.

It's just... when you check in-game, the little white mark on the ILS is OFF in this particular position. When you move it to the "PWR" position, the lights are off again. This leads me to the question, if this is an DCS display bug - and if so: what do I do about it? How do I invert the value? And besides - how do I combine this with checking if Battery Power is indeed on? I speak Java, but I'm still struggling with the Arduino language, especially when a powerful library like DCS-BIOS is involved.  I guess I need to instantiate some object that holds the "Battery Power" Value, check this and then invert the "ILS Power" value.

Could anyone maybe give me a little code snippet to push me in the right direction, please?

**Comment by jboecker** [comment]
> when you check in-game, the little white mark on the ILS is OFF in this particular position.
You are reading the in-game switch wrong. Here's a close up of the ILS power knob:

![image](https://cloud.githubusercontent.com/assets/158946/19736196/93e7974c-9bae-11e6-98b8-ca1dc628e6d5.png)

It is currently switched on. Note that the white tick mark is the label. The "pointer" is a little triangle attached to the knob that covers part of the white tick mark for the "on" label. It's easy to see in the image above, but I can see where you are coming from when looking at the same situation from the snapview:
![image](https://cloud.githubusercontent.com/assets/158946/19736318/0b562d66-9baf-11e6-86f8-a45e2a3cad35.png)
